### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by MarkOlijslagers** [codemonauts/craft-instagram-feed#16]
When i add 'craft.instagram.getFeed()' in my templates, it results in an internal server error.
yii\base\ErrorException: Undefined offset: 1 in /var/www/vhosts/sitename.com/httpdocs/vendor/codemonauts/craft-instagram-feed/src/services/InstagramService.php:73

**Comment by kringkaste** [comment]
Can you tell me the username where the error occurs? This must be a special case.

**Comment by MarkOlijslagers** [comment]
Dopesn’t matter which instagram username is used. All of them result with an error.

On this page:
https://heroesdenbosch.com/instatest

This code is used:
{% for item in craft.instagram.getFeed('codemonauts') %}
<a href="https://www.instagram.com/p/{{ item.shortcode }}/" target="_blank">
 <img src="{{ item.src }}" alt="" />
</a>
<p>{{ item.caption }}</p>
<p>{{ item.likes }} Likes / {{ item.comments }} Comments</p>
{% endfor %}

Stacktrace:

yii\base\ErrorException: Undefined offset: 1 in /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/codemonauts/craft-instagram-feed/src/services/InstagramService.php:73 Stack trace: #0 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/vhosts...', 73) #1 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/codemonauts/craft-instagram-feed/src/services/InstagramService.php(73): craft\web\ErrorHandler->handleError(8, 'Undefined offse...', '/var/www/vhosts...', 73, Array) #2 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/codemonauts/craft-instagram-feed/src/services/InstagramService.php(36): codemonauts\instagramfeed\services\InstagramService->getInstagramData('codemonauts') #3 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/codemonauts/craft-instagram-feed/src/variables/InstagramFeedVariable.php(11): codemonauts\instagramfeed\services\InstagramService->getFeed('codemonauts') #4 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/twig/twig/src/Extension/CoreExtension.php(1485): codemonauts\instagramfeed\variables\InstagramFeedVariable->getFeed() #5 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(codemonauts\instagramfeed\variables\InstagramFeedVariable), 'getFeed', Array, 'method', false, false) #6 /var/www/vhosts/heroesdenbosch.com/httpdocs/storage/runtime/compiled_templates/47/473b14678d71870b830744a86d02eedaa6af590443a646579e28e60df14210c2.php(39): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(codemonauts\instagramfeed\variables\InstagramFeedVariable), 'getFeed', Array, 'method') #7 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/twig/twig/src/Template.php(407): __TwigTemplate_4c71015551f2f30474a33b769d1edaffed2ab29b3ac102930aa3c40e5b003971->doDisplay(Array, Array) #8 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array) #9 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array) #10 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array) #11 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array) #12 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('instatest', Array) #13 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/web/View.php(392): craft\web\View->renderTemplate('instatest', Array) #14 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('instatest', Array) #15 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('instatest', Array) #16 [internal function]: craft\controllers\TemplatesController->actionRender('instatest', Array) #17 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #18 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #19 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array) #20 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array) #21 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array) #22 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array) #23 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request)) #24 /var/www/vhosts/heroesdenbosch.com/httpdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request)) #25 /var/www/vhosts/heroesdenbosch.com/httpdocs/web/index.php(21): yii\base\Application->run() #26 {main}

Met vriendelijke groet,
Mark Olijslagers


Get Hooked B.V.
De Grote Beer 10 • 5215 MP ’s-Hertogenbosch
+31 (0)85 747 00 31 • mark@gethooked.nl • www.gethooked.nl
Werkzaam op: ma, wo, do en vr

De algemene verkoopvoorwaarden van Get Hooked zijn van toepassing op alle aanvragen, offertes, opdrachten en overeenkomsten. De algemene verkoopvoorwaarden bevatten een exoneratieclausule en een forumkeuze voor de rechter van de vestigingsplaats van Get Hooked. De algemene verkoopvoorwaarden zijn gedeponeerd bij de Kamer van Koophandel te ’s-Hertogenbosch en liggen op het kantoor van Get Hooked ter inzage. Op uw verzoek zullen wij te allen tijde en kosteloos een kopie van de algemene verkoopvoorwaarden aan u toezenden. De algemene verkoopvoorwaarden zijn daarnaast te raadplegen op onze website (https://www.gethooked.nl/algemenevoorwaarden/) en aldaar in te zien, te downloaden en op te slaan. De toepasselijkheid van eventuele algemene voorwaarden van de wederpartij wordt uitdrukkelijk van de hand gewezen.
On 10 Sep 2019, 23:32 +0200, Tom Schulze <notifications@github.com>, wrote:
> Can you tell me the username where the error occurs? This must be a special case.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


De algemene verkoopvoorwaarden van Get Hooked zijn van toepassing op alle aanvragen, offertes, opdrachten en overeenkomsten. De algemene verkoopvoorwaarden bevatten een exoneratieclausule en een forumkeuze voor de rechter van de vestigingsplaats van Get Hooked. De algemene verkoopvoorwaarden zijn gedeponeerd bij de Kamer van Koophandel te ’s-Hertogenbosch en liggen op het kantoor van Get Hooked ter inzage. Op uw verzoek zullen wij te allen tijde en kosteloos een kopie van de algemene verkoopvoorwaarden aan u toezenden. De algemene verkoopvoorwaarden zijn daarnaast te raadplegen op onze website (https://www.gethooked.nl/algemenevoorwaarden/) en aldaar in te zien, te downloaden en op te slaan. De toepasselijkheid van eventuele algemene voorwaarden van de wederpartij wordt uitdrukkelijk van de hand gewezen.

**Comment by bymayo** [comment]
@MarkOlijslagers Is the instagram profile private? Or does it not exist? Because I see you used `codemonauts` example, but this doesn't even exist.

This plugin only works by scraping content from public profiles.

**Comment by kringkaste** [comment]
@MarkOlijslagers Please test the new 1.0.3 release and make use of the Guzzle instead of the php's file stream. May this can help. We also added an debug output in dev mode. So if you still get an error, you can see what your server fetched from Instagram. That could help debugging your problem.

**Comment by MarkOlijslagers** [comment]
Afer updating to 1.0.3 and add the setting 'useGuzzle' => true, the server error still remains.
When i install the plugin on another website, the same server error appears.
Is this plugin compatible with Craft 3.2.x and 3.3.x?
Also a server error is given when saving the settings page in the cp of the plugin (/admin/settings/plugins/instagramfeed)

**Comment by kringkaste** [comment]
Ok, in devMode you should see a lot of log lines in web.log from the plugin. Can you grep them and save the HTML block to e.g. codepen so I can review them? Be sure to have cleared the data cache before.

The bug with the settings will be fixed asap. Thanks for reporting it.

**Comment by MarkOlijslagers** [comment]
Codepen didn't accept the code, so i've uploaded a static file:
https://heroesdenbosch.com/instatest-stacktrace
The cache was cleared before.

**Comment by kringkaste** [comment]
That's strange. You got an answer as JSON and not HTML and that's maybe the problem. Can you switch to guzzle instead of file stream and try again and upload the stack trace again. Maybe we will see some more informations.

**Comment by MarkOlijslagers** [comment]
Switched to Guzzle: https://heroesdenbosch.com/instatest-stacktrace-2

**Comment by kringkaste** [comment]
Ok, same response. Could it be, that your IPs are blacklisted bei Instagram? Did you try too many times or tried other "scrapers" as well? Please test your installation on another host with different IP range. I get your Instagram feed from "heroesdenbosch" with this plugin - here at home as well on our servers in different data centers.

We catch this behavior with release 1.0.4 (just released) but this won't help you, you will not get any errors, but your feed will be empty. Sorry, I can't do anything else at the moment.

**Comment by timdmp** [comment]
i am afraid you are right, the plugin works without problems while running the website local or on another server.

**Comment by MarkOlijslagers** [comment]
i am afraid you are right, the plugin works without problems while running the website local or on another server.

**Comment by kringkaste** [comment]
I'm sorry to hear that. From my experience I can say that it is impossible to have the blocking removed. I will close the issue now. Good luck!

**Comment by fleaz** [comment]
Hey,

because multiple of our customers who use this plugin faced the same problem of beeing blacklisted by Instagram and therefore couldn't use our plugin, we started to implement a new feature which will circumvent this and use a proxy server to get the data.
If you still have this problem and wan't to give our plugin another chance, we would love to have you in our beta test for the next version.

Just write a mail to support@codemonauts.com and we will give you a beta key and all the details on how to use it :)

Best regards,
Felix
