### ISSUE TITLE
Getting username from dynamically from entry

### ISSUE THREAD

**Issue by DaveBeirne** [codemonauts/craft-instagram-feed#22]
Is it possible to get the username dynamically from the entries?

`{% for item in craft.instagram.getFeed("{{ entry.InstagramUrl }}")[:3] %}
        <div class="gallery"><img src="{{ item.src }}" alt="{{ item.shortcode }}"></div>
   {% endfor %}`

** {{ entry.InstagramUrl }} is a custom field pulled from the CMS

This would allow a user to update it from the CMS

**Comment by DaveBeirne** [comment]
Any help would be appreciated thanks :)

**Comment by fleaz** [comment]
Paging @kringkaste 

He can probably help you with this or at least evaluate if its possible with the current version of the plugin :)

**Comment by DaveBeirne** [comment]
Any help @kringkaste would be appreciated

**Comment by Harry-Harrison** [comment]
I could be wrong and havent tested this, but wouldnt this be the fix?

```
{% for item in craft.instagram.getFeed(entry.InstagramUrl)[:3] %}
    <div class="gallery">
        <img src="{{ item.src }}" alt="{{ item.shortcode }}">
    </div>
{% endfor %}
```

**Comment by fleaz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Instagram: Username aus entry auslesen](https://trello.com/c/qFMZq1Yq/25-instagram-username-aus-entry-auslesen)

**Comment by kringkaste** [comment]
@DaveBeirne You can pass the Instagram username (not the complete URL) from an entry's field to the function like @Harry-Harrison commented before. That works.
