### ISSUE TITLE
Configuration of multiple Instagram Accounts

### ISSUE THREAD

**Issue by maltemichels** [codemonauts/craft-instagram-feed#23]
Is it possible to configure multiple accounts within one craft installation?

**Comment by fleaz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [instagram: Multi account](https://trello.com/c/EWEVjiJZ/26-instagram-multi-account)

**Comment by jdsimcoe** [comment]
I have the same question. The large site I work on has multiple accounts.

**Comment by jdsimcoe** [comment]
Actually @maltemichels it looks like this bit from the documentation might answer our question:

![image](https://user-images.githubusercontent.com/275617/77803101-972d5a00-7039-11ea-9272-ea79de2394dc.png)

**Comment by jdsimcoe** [comment]
In templates you can override the account.

**Comment by maltemichels** [comment]
Indeed @jdsimcoe — thanks for the hint!
