### ISSUE TITLE
Plug-in doesn't work on Craft CMS 3.3.17

### ISSUE THREAD

**Issue by marcelvillerius** [codemonauts/craft-instagram-feed#24]
Since the last update (Craft CMS 3.3.17) Craft Instagram Feed doesn't work anymore.

**Comment by marcelvillerius** [comment]
Sorry, too quick. It's working local, but not live. So it's the same as issue #4

**Comment by fleaz** [comment]
Hey @marcelvillerius,
sorry to hear that you have a problem with our plugin. "working locally but not on live site" often means that you triggered some kind of bot detection at Instagram and the won't let you see the profile page anymore without logging in. Can you follow the instructions in https://github.com/codemonauts/craft-instagram-feed/issues/21#issuecomment-541001390 to get a debug dump of the response the plugin gets from IG? Than we can have a look at it and try to debug it

**Comment by marcelvillerius** [comment]
Hi @fleaz,
Thank you for your quick response!  
I need a bit more information to follow the instructions in #21:
- How do I upgrade the plugin to "dev-master"?
- Should I change dumb to 'true' in the config file?
- Can I find the dump in /storage/runtime?
Thank you for helping me out!

**Comment by marcelvillerius** [comment]
I just checked the website, and I was surprises tot see that it's working now.. Thanks again!

**Comment by fleaz** [comment]
> I just checked the website, and I was surprises tot see that it's working now..

Now I'm pretty sure it was a problem with beeing blocked by IG


But nontheless I will answer the questions. So everybody learns something and maybe someday in the future people with the same problem will stumble across this :)

1. You can use "dev-master" as the version number in your composer file. This way you tell composer to pull the plugin directly from git and not from a released version. Therefore you get all the changes which are already in the repository but not jet released. It will look somehting like this in your file:
```
  "require": {
    ...
    "codemonauts/craft-instagram-feed": "dev-master",
    ....
}
```

2. Yes, you should. By changing it to "true" you enable the  `dump` feature and the plugin will dump the response it gets from IG to a file.

3. Yes, there will be a new folder in your `runtime` drectory called `instagramfeed` where you can find the generated files

**Comment by marcelvillerius** [comment]
Thank you Felix!

**Comment by fleaz** [comment]
Hey,

because multiple of our customers who use this plugin faced the same problem of beeing blacklisted by Instagram and therefore couldn't use our plugin, we started to implement a new feature which will circumvent this and use a proxy server to get the data.
If you still have this problem and wan't to give our plugin another chance, we would love to have you in our beta test for the next version.

Just write a mail to support@codemonauts.com and we will give you a beta key and all the details on how to use it :)

Best regards,
Felix
