### ISSUE TITLE
Limit feed items

### ISSUE THREAD

**Issue by fbnntt** [codemonauts/craft-instagram-feed#25]
Hi

I know the plugin pulls in the first 12 images, but I was wondering if there's a way to make the limit customisable? 

I'm only looking to grab the first 4—6 posts.

Any help would be appreciated. Thanks!

**Comment by fbnntt** [comment]
Nevermind. I just used `|batch(4)|first` to get what I wanted.

**Comment by masiorama** [comment]
In case anyone is interested, another solution is represented by _slice_ filter.
For example `| slice(0,8)` will retrieve only the first 8 entries.
