### ISSUE TITLE
Will this stop working March 20 ?

### ISSUE THREAD

**Issue by DaveBeirne** [codemonauts/craft-instagram-feed#27]
https://developers.facebook.com/blog/post/2020/01/14/instagram-basic-display-api-long-lived-access-tokens-available/

**Comment by sam327** [comment]
March 2nd, not 20th!

**Comment by fleaz** [comment]
Hi @DaveBeirne 

our plugin is not using the Instagram API but instead directly accesses the website just like a browser and scrapes the images. Therefore we are not affected by this change.

Best,
Felix
