### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by mbuskies** [codemonauts/craft-instagram-feed#29]
Using the following code it outputs all of the text (caption, likes, comments) but not the image. The image URL is being loaded in the code but not shown on the website. I'm developing locally. Any ideas why this would be happening? Thanks!

```
{% for item in craft.instagram.getFeed() %}
<a href="https://www.instagram.com/p/{{ item.shortcode }}/" target="_blank">
  <img src="{{ item.src }}" alt="" />
</a>
<p>{{ item.caption }}</p>
<p>{{ item.likes }} Likes / {{ item.comments }} Comments</p>
{% endfor %}
```

**Comment by kringkaste** [comment]
Hi! If you see the image URLs in the source of your page but they will not displayed, maybe the browser gives you the answer in his console window? Can you check this in your development console? What HTTP return code have the requests to the images?

**Comment by mbuskies** [comment]
Hi, I will try and do that and post what I come up with. Thank you!

**Comment by jdsimcoe** [comment]
@kringkaste I'm getting `403` errors on https://atheycreek.com. It only happens for video posts:

```
Failed to load resource: the server responded with a status of 403 ()
```

You can go to the URL above and see it in action.

**Comment by fleaz** [comment]
Hi @jdsimcoe 
just a few days ago I saw this feature working on a customer site, so IG must have made some changes in the last few days which broke the plugin. We will look into this and try to fix it. Thanks for the report :)

**Comment by jdsimcoe** [comment]
Thanks @fleaz. Appreciate the help.

**Comment by jdsimcoe** [comment]
@kringkaste @fleaz I should add that on my local dev server everything is working fine. On production, the feed is not updating at all and I'm getting 403 errors.

**Comment by ljclark** [comment]
I'm also getting this same error - works fine locally, but no images appearing on production.

**Comment by DaveBeirne** [comment]
yes i am also getting no images loading and it worked previously with your plugin :(

**Comment by fleaz** [comment]
Hey @DaveBeirne as mentioned in the previous comment, just drop as a mail and we will provide you with the details on how to use our proxy :)

**Comment by richhayler** [comment]
Hi @fleaz, I’m also running into the same issue as described above. I’ve sent an email to support@codemonauts.com requesting access to your proxy. Happy to help with any testing or workarounds. Thanks.

**Comment by richhayler** [comment]
Thanks for the help @fleaz 👍
