### ISSUE TITLE
Limit feed items

### ISSUE THREAD

**Issue by spoeken** [codemonauts/craft-instagram-feed#3]
How would you go about limiting the number of images to show?

**Comment by spoeken** [comment]
This works, but will the array actually contain all images ever posted? 
`{% for item in craft.instagram.getFeed()[:7] %}`

**Comment by kringkaste** [comment]
We only fetch the newest 12 images from the public profile page. So, the array doesn't contain the hole timeline.

**Comment by spoeken** [comment]
@kringkaste Thank you for the clarification!
