### ISSUE TITLE
Possible to limit # of images returned?

### ISSUE THREAD

**Issue by richhayler** [codemonauts/craft-instagram-feed#34]
Just asking if there is a config setting or query parameter to limit the number of instagram images returned?

**Comment by kringkaste** [comment]
HI Rich, no there is no parameter to limit the number of images returned. It's always 12. It's an array and if you want to limit it, just use `|splice` or something like this.

**Comment by fleaz** [comment]
Hey @richhayler ,
have a look over here where someone else had the same question and posted the solution: https://github.com/codemonauts/craft-instagram-feed/issues/25#issuecomment-572775768
