### ISSUE TITLE
New user - no entries loaded - error below

### ISSUE THREAD

**Issue by TUSAB-web** [codemonauts/craft-instagram-feed#41]
I am just trying out this plugin, and it isn’t able to pull anything from instagram. I saw this error in my log:

[-][1][-][error][codemonauts\instagramfeed\services\InstagramService::getInstagramAccountData] Instagram profile data could not be fetched. Maybe the site structure has changed.

I noticed recently Instagram changed such that you can’t even see public profiles on the web without logging in? Or maybe my IP (local machine) is blocked by instagram? Not sure.

**Comment by fleaz** [comment]
> I noticed recently Instagram changed such that you can’t even see public profiles on the web without logging in?

I can't confirm this. To our knowledge Instagram has not started to block private IP addresses. Do you maybe have a VPN running?

But yes, if you can't even open an Instagram profile in your browser, the plugin also can't do this and generates the error message you provided. If you want, you can check #32 and send me an email to get access to our proxy.

Best,
Felix

**Comment by TUSAB-web** [comment]
I get the same issue when running it on the server (Azure) so I will shoot you an email. Thanks!
