### ISSUE TITLE
URL signature expired for videos

### ISSUE THREAD

**Issue by perry-garvin** [codemonauts/craft-instagram-feed#42]
Plugin is working very well but just for videos no image loads and a console log error appears:

```139702539_435660231134195_1029140841979079187_n.jpg:1 Failed to load resource: the server responded with a status of 403 ()```

If I try to load the image URL in the browser it says: `URL signature expired`

Photos and slideshows are loading just fine. This problem just occurs with video as far as I can tell. Any ideas?

**Comment by mdominguez** [comment]
Getting this too on all of our sites..

**Comment by perry-garvin** [comment]
I emailed the developers and they helped me out. See this for more info: https://github.com/codemonauts/craft-instagram-feed/issues/32
