### ISSUE TITLE
cURL from proxy fails with GuzzleHttp\Exception\ConnectException cURL error 28

### ISSUE THREAD

**Issue by sonoflee** [codemonauts/craft-instagram-feed#48]
Recently configured with proxy as described in #32. Things were working OK on both dev and staging, but now all pages that incorporate the plugin generate internal server error:

> GuzzleHttp\Exception\ConnectException cURL error 28: 
> Operation timed out after 10002 milliseconds with 0 bytes received

**Comment by kringkaste** [comment]
Please update to the latest version 1.0.6 which prevents this error.
