### ISSUE TITLE
Undefined index: has_audio

### ISSUE THREAD

**Issue by CharlieGentle** [codemonauts/craft-instagram-feed#49]
Just updated to 1.0.6 and now getting this:

PHP Notice – yii\base\ErrorException
Undefined index: has_audio

/vendor/codemonauts/craft-instagram-feed/src/services/InstagramService.php

307: $item['hasAudio'] = $item['isVideo'] ? (bool)$media['node']['has_audio'] : false;

**Comment by kringkaste** [comment]
Ok, thats interesting. A video without the audio infomration. Could you tell me the Instagram account to check this?

**Comment by CharlieGentle** [comment]
I'm pulling through a hashtag if that changes anything. Testing a few and the one that gave me this problem was #dogsofinstagram

**Comment by kringkaste** [comment]
Thank you! We had not seen this kind of video meta before. I fixed this and released a new version 1.0.7.
