### ISSUE TITLE
Liquid Variable not working in the space of Username

### ISSUE THREAD

**Issue by JMKelley** [codemonauts/craft-instagram-feed#5]
{% set ig = user.instagram|split('/')|slice(3, 3)|join %}
    {{ ig }}
    {% set items = craft.instagram.getFeed("{{ ig|spaceless }}") %}

Doing this makes the feed not load at all, but when inserting the text the variable prints manually it works perfectly?

**Comment by kringkaste** [comment]
Hi! Following is working here:

```twig
{% set ig = user.instagram|split('/')|slice(3, 3)|join %}
{{ ig }}
{% set items = craft.instagram.getFeed(ig|spaceless) %}
```
You can pass a variable to the function. Or did I miss something?

**Comment by JMKelley** [comment]
@kringkaste Had a bit of a lapse in coding. I forgot to remove this. Your code works perfectly.
