### ISSUE TITLE
New system, S3, dev <> prod

### ISSUE THREAD

**Issue by bossanova808** [codemonauts/craft-instagram-feed#52]
Hi Folks 

Spent the morning implementing your new system.  Thanks for making the changes, and so quickly.

I got it working on dev, after some mucking about - might be worth noting in your docs that during testing it is handy to clear caches as basically if there is an issue with e.g. saving an image, you can't really fix this without clearing the cache (it seems).

Once I had it working and saving the images to our volume (on S3), I then uploaded the changes to production.

It did not work there....checking the logs I see:

```
2021-04-30 11:55:52 [-][1][-][error][application] Could not save Instagram image to volume: A file with the name “CN9WShFDNCN.jpg” already exists.
2021-04-30 11:55:53 [-][1][-][error][application] Could not save Instagram image to volume: A file with the name “CNrTYoZAtGA.jpg” already exists.
2021-04-30 11:55:53 [-][1][-][error][application] Could not save Instagram image to volume: A file with the name “CNmBGgQjPN0.jpg” already exists.
2021-04-30 11:55:53 [-][1][-][error][application] Could not save Instagram image to volume: A file with the name “CNWMrIxDCTO.jpg” already exists.
(etc)
```

So it seems it was (not surprisingly) trying to re-download the images as it built the feed cache on production.  Given they already exist, you would think this would work, but the images were missing on loading the page in question on production - I had to manually delete them from our s3 bucket, clear cached, and re-load before the production server would display the images.  I presume the local feed cache does not get built with such errors encountered - but really if they exist on the volume, it should just point at them, shouldn't it?  Otherwise folks will likely have regular problems moving between dev and prod, I think.

Of course I may well be misunderstanding something here...please let me know if so!

**Comment by fleaz** [comment]
Hey,

when saving the images to a volume, our plugin creates an actual `Asset`object in your Craft site which gets an entry in the database. When you now use the same bucket for prod and dev and open your prod website, the Assets are not in the prod database therefore our plugin thinks it needs to download them and then fails to save them, because a file with the same name already exists in the bucket, which normally can never happen and we therefore don't catch this edge case.

>  Otherwise folks will likely have regular problems moving between dev and prod, I think.

I would suggest you to use seperate S3 buckets for prod and dev which is imho the normal way to do it, therefore I don't think a lot people will face this issue.

How e.g. do you test file uploads locally? These files would all be saved to the prod bucket which will result in a pretty mess, doesn't it? 

But I just talked to our dev and asked if we can implement an easy check in our plugin to catch this scenario.


Best,
Felix

**Comment by chanhman** [comment]
Sorry to hijack, but I tried clearing my cache, set ` Use volume to store the Instagram images` to true, set where the images should be downloaded, but can't seem to get it to work. Is there a trigger that needs to be done? I checked the logs but there was nothing useful like the OP's.

**Comment by bossanova808** [comment]
Hi Felix

Actually it's super common to develop this way - over the years I have sees many devs talking about using this exact approach regularly in e.g. the Craft Slack/Discord.  It allows a single pool of assets shared between dev and client so content creation and high quality assert gathering can begin much earlier in the dev process...which of course can significantly ease the dev/design as you can move more quickly to using 'real things' as you work.  Pretty sure it's come up in the devMode podcast along the way, even.    It's definitely not an edge case!

Thanks for considering it, anyway

Jeremy

**Comment by fleaz** [comment]
@chanhman Hey. Can you further elaborate on "can't seem to get it to work"? Does the plugin create the "Instagram" folder in the volume? Are there images in the volume? Are you using the plugin with the proxy or without? Was it working before or is this a new installation?


@bossanova808 Oh okay, this sounds indeed quite common. None of us here was aware of this approach, sorry about that. We always use seperate buckets for every stage with an automatic one-way-sync from prod to dev/stage so you always have all the up to date assets from the client but you can never accidentally delete/modify/etc something that has impact on the live site which was our reason to do this. And storage itself is super cheap so it doesn't hurt to save every assets twice in different buckets.

But now that we are aware that this is so common, we definitely will make the plugin work with this bucket setup. Thanks for bringing this up and telling us about it! :+1:

**Comment by chanhman** [comment]
> Does the plugin create the "Instagram" folder in the volume? 

Yup!

> Are there images in the volume? 

Nope :(

> Are you using the plugin with the proxy or without? 

Without

> Was it working before or is this a new installation?

New

I doubled check the steps in the readme, but I can't seem to get the plugin to add the images from Instagram to the volume. Head scratcher.

**Comment by fleaz** [comment]
Hey @chanhman 

if you have an empty instagram folder, I'm pretty sure you hit #32.

Just write us an email an we can add you to the proxy :)

**Comment by bossanova808** [comment]
Fix for this would be great...any further thoughts?

**Comment by bartrylant** [comment]
Hi

I'm having the same problem. Using a shared S3 bucket for dev and production. Works fine on dev, does not on production. If I check the source code for production, this is the code for thumbnails:

`<img src="/instagramfeed/thumb/CPLFghQDITZ" width="150" alt="Instagram afbeelding">`

If I check it on dev (where the images work), the code is

`<img src="https://xxxxxxxxxxxx.cloudfront.net/uploads/other/insta/CPLFghQDITZ.jpg?mtime=20210614160942&amp;focal=none" width="150" alt="Instagram afbeelding">`

**Comment by fleaz** [comment]
Hey,
we didn't forgot you :)

We just had to fix the issue with  accessing hashtags first, because this impacted more people. We already know what's the root cause for this issue here and we will fix it with the next release. Sorry for the waiting time.

**Comment by kringkaste** [comment]
@bartrylant Its seems, that you have two different configurations in dev and prod. Your production configuration uses the local storage and your dev environment has the volume configured. This seems to be a different problem. How do you configure the plugin? With the settings in CP or with an instagramfeed.php in the config directory?

**Comment by kringkaste** [comment]
@bossanova808 We have released 1.1.5 which will fix the problem.

**Comment by kringkaste** [comment]
Hey @bartrylant maybe I found the problem you have. Can you update to the latest version 1.1.5 and clear your data cache?

**Comment by bossanova808** [comment]
Ok, will give it a try - thanks!   (after deploy I still had a missing image and had to clear my data cache, but the images showed up after that...)

**Comment by bartrylant** [comment]
I only use the instagramfeed.php config file. I disabled the option to edit settings on production, so I don’t know why it would use other setting on production though.

**Comment by kringkaste** [comment]
@bartrylant Could you test the latest version?

**Comment by bartrylant** [comment]
Yup that did fix it. Thank you
