### ISSUE TITLE
Instagram feed suddenly disappeared.

### ISSUE THREAD

**Issue by azim1728** [codemonauts/craft-instagram-feed#54]
the plugin was working fine for us with the hashtag but suddenly the feeds disappeared. FYI it wasn't working with username.

**Comment by kringkaste** [comment]
Hi! Do you use the latest version 1.1.4 of our plugin? The structure of the hashtag data has changed and we had to update our code.

**Comment by azim1728** [comment]
yes I am using the latest version. i.e 1.1.4
![Screenshot_103](https://user-images.githubusercontent.com/54146953/122116427-39a24a80-ce43-11eb-9006-8e909f374c5b.jpg)

**Comment by fleaz** [comment]
Fixed via Email. Hashtag was removed by Instagram.
