### ISSUE TITLE
Plugin doesn't work for public Instagram account

### ISSUE THREAD

**Issue by rahulanair** [codemonauts/craft-instagram-feed#57]
Hi,
This plugin doesn't work for a public Instagram account. It is not returning any feeds when using a username.
But it is just working fine when we use hashtags. Can you fix this?

Thanks

**Comment by fleaz** [comment]
If this happens on a server and with multiple accounts I would assume that you are hitting #32. Please write us a email to support@codemonauts.com and we can provide you with a key to our proxy which should fix this :)

**Comment by rahulanair** [comment]
Proxy key did the trick. Thank you :)
