### ISSUE TITLE
Public username not loading posts but hashtag does

### ISSUE THREAD

**Issue by satcreative** [codemonauts/craft-instagram-feed#60]
**Describe the bug:**
Defining the getFeed() source using a public username renders nothing; however declaring a hashtag as the source does load posts, so issue seems to be specific to account name. Does the username declaration no longer work?

**Steps to reproduce:**
1. craft.instagram.getFeed('manchesterunited') --- renders nothing
2. craft.instagram.getFeed('#manchesterunited') --- renders posts

**Where is it happening?**
  * On a server
  * Local dev environment

**What are you requesting:**
Username: 'manchesterunited'
Hashtag: '#manchesterunited'

**Software versions:**
Plugin Version: 1.1.7
PHP Version: 8.0.16
CraftCMS Version: 3.7.30.1

**Comment by fleaz** [comment]
Hey,

could you please create a [config file](https://plugins.codemonauts.com/plugins/instagramfeed/Configuration.html) for the plugin, set `dump` to true and request the account again? This way you should get a "runtime/intagramfeed/" folder with a file containing the plain HTML response our plugin got from Instagram. By looking at this, we can probably identify what the problem is.

Best,
Felix

**Comment by satcreative** [comment]
Hi Felix,

Thanks for the quick response.

I've done as you suggest and have generated a runtime response for both 'manchesterunited' and '#manchesterunited' (the examples I'm using are purely random to allow me to test)

You can see the difference here - https://www.diffchecker.com/t97EQVso

I can see the the 'manchesterunited' response suggests it was trying to login and perhaps was denied. 

Gary

**Comment by fleaz** [comment]
Thanks fot the output.

That you get redirected to the "Login" page when requesting something, is quite a clear sign that you hit #32.  You can drop us a short email on crew@codemonauts.com and I will provide you with a key to our proxy. This should fix this issue for you :)

But interessting that they treat acounts and hashtags differently. Haven't seen this before.

**Comment by satcreative** [comment]
The proxy worked easily to solve this issue for me
