### ISSUE TITLE
Does the latest version work on Craft CMS 3?

### ISSUE THREAD

**Issue by mark-chief** [codemonauts/craft-instagram-feed#63]
Does the latest version work on Craft CMS 3?

We are unable to move to Craft 4 just yet due to other plugin inconsistencies. 

Thanks

**Comment by fleaz** [comment]
Yes, it does. We were aware that not everybody can upgrade to Craft4 immediately so we continue Craft3 Support in all of our plugins. We bumped the major version number up to make it clear: Version `2.x` required Craft4 and `1.x` is still for Craft3 and contains the same *business logic* as the latest version in the `2.x` branch :)
