### ISSUE TITLE
Plugin seems to have stopped working

### ISSUE THREAD

**Issue by vandres** [codemonauts/craft-instagram-feed#67]
**Describe the bug:**

We use this plugin for a while. You've generously provided us proxy access. Lately we don't get any new Instagram posts and requesting the feed no longer consists of an `asset` property (only the cached ones). We use a volume to save the result. 

**Steps to reproduce:**
1. Configure a volume
2. Use "event.core" as handle
3. See the code below
4. Result: No Instagram items are displayed

**Where is it happening?**
  * [x] On a server
  * [x] Local dev environment

**What are you requesting:**
Username: event.core

**Config file:**

```php
return [
    'proxyKey' => '9fPfJXXXXXXXXX',
    'useProxy' => true,
    'timeout' => 10,
];
```

**Software versions:**
Plugin Version: 1.2.0
PHP Version: 8.0.24
CraftCMS Version: 3.7.63.1

** Code **

```twig
{% set handle = global.instagram %}
{% if handle %}
    {% set items = craft.instagram.getFeed(handle) %}
    {% if items %}
        <div class="instagram-container">
            {% for item in items | slice(0, 6) %}
                {% if item.asset is defined %}
                    <a class="instagram {{ item.isVideo ? 'video' : '' }}" href="https://www.instagram.com/p/{{ item.shortcode }}/" target="_blank" rel="noopener noreferrer">
                        {% include 'laser/_includes/_fields/image' with {'image': item.asset, 'manipulation': 'instagram'} %}
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% endif %}

```

**Comment by fleaz** [comment]
Hey,

from what I can see, the account "event.core" was new to the proxy and requested for the first time. We had a small problem with new accounts but from what I can see it should be resolved now and I already saw valid requests against the account "event.core".

Can you confirm that it's working now?

Sorry for  the inconvenience,
Felix

**Comment by vandres** [comment]
Hi Felix

Yes! I can see the thumbnails now again :) Thank you!
