### ISSUE TITLE
Page Speed

### ISSUE THREAD

**Issue by JMKelley** [codemonauts/craft-instagram-feed#7]
Is there a way to increase the page load speed? I'm caching for 3 weeks also within my templates but the initial load is fairly slow.

**Comment by kringkaste** [comment]
How "slow" is slow? I think we do not have any chance to increase the page load on Instagram. We have to fetch the hole page and parse it. And there are a lot of influencing factors.

You can now set a timeout for fetching the Instagram page. May this help you.

**Comment by kringkaste** [comment]
Closed du to inactivity.
